export const permissionCodes = [
  'organization.read',
  'organization.update',
  'facility.create',
  'facility.read',
  'facility.update',
  'audit.read',
  'clinician.create',
  'clinician.read',
  'clinician.update',
  'specialty.create',
  'specialty.read',
  'specialty.update',
  'payer.create',
  'payer.read',
  'payer.update',
  'tpa.create',
  'tpa.read',
  'tpa.update',
  'network.create',
  'network.read',
  'network.update',
  'service.create',
  'service.read',
  'service.update',
  'procedure_code.create',
  'procedure_code.read',
  'procedure_code.update',
  'diagnosisCode.create',
  'diagnosisCode.read',
  'diagnosisCode.update',
  'external_identifier.create',
  'external_identifier.read',
  'external_identifier.update',
  'rule_source.create',
  'rule_source.read',
  'rule_source.update',
  'rule_source_version.create',
  'rule_source_version.read',
  'source_interpretation.create',
  'source_interpretation.read',
  'source_interpretation.update',
] as const

export type PermissionCode = (typeof permissionCodes)[number]

export type AccessDecision =
  | { allowed: true; permissions: PermissionCode[] }
  | { allowed: false; reason: 'UNAUTHENTICATED' | 'NOT_MEMBER' | 'FORBIDDEN' }
