export const permissionCodes = [
  'organization.read',
  'organization.update',
  'facility.create',
  'facility.read',
  'facility.update',
  'audit.read',
  'clinician.create',
  'clinician.read',
  'clinician.update',
  'specialty.create',
  'specialty.read',
  'specialty.update',
  'payer.create',
  'payer.read',
  'payer.update',
  'tpa.create',
  'tpa.read',
  'tpa.update',
  'network.create',
  'network.read',
  'network.update',
  'service.create',
  'service.read',
  'service.update',
  'procedure_code.create',
  'procedure_code.read',
  'procedure_code.update',
  'diagnosisCode.create',
  'diagnosisCode.read',
  'diagnosisCode.update',
  'external_identifier.create',
  'external_identifier.read',
  'external_identifier.update',
  'rule_source.create',
  'rule_source.read',
  'rule_source.update',
  'rule_source_version.create',
  'rule_source_version.read',
  'source_interpretation.create',
  'source_interpretation.read',
  'source_interpretation.update',
  'rule_source_version.lifecycle',
  'rule_source_relationship.create',
  'rule_source_relationship.read',
  'rule_definition.create',
  'rule_definition.read',
  'rule_definition.update',
  'rule_version.create',
  'rule_version.read',
  'rule_version.update',
  'rule_version.verify',
  'rule_applicability.create',
  'rule_applicability.read',
  'rule_source_binding.create',
  'rule_source_binding.read',
  'rule_executability.evaluate',
  'facility_regulatory_profile.create',
  'facility_regulatory_profile.read',
  'facility_regulatory_profile.update',
  'facility_regulatory_profile.activate',
  'insurance_product.create',
  'insurance_product.read',
  'insurance_product.update',
  'product_network.create',
  'product_network.read',
  'provider_contract.create',
  'provider_contract.read',
  'provider_contract.update',
  'contract_facility.create',
  'contract_facility.read',
  'tariff_schedule.create',
  'tariff_schedule.read',
  'tariff_schedule.update',
  'tariff_schedule_version.create',
  'tariff_schedule_version.read',
  'tariff_schedule_version.lifecycle',
  'reference_dataset.read',
  'rule_source_scope.create',
  'rule_source_scope.read',
  'rule_resolution.read',
  // A3.9 — the only two new permissions. There is deliberately no rule_provenance.read.
  'rule_pack.read',
  'rule_pack.write',
  // A4.1 — Patient identity only. There is deliberately no patient.delete, patient.merge,
  // patient.external_id or patient.insurance permission.
  'patient.create',
  'patient.read',
  'patient.update',
  // A4.2 — one permission family covers both assignment types. There is deliberately no update or
  // delete permission: an assignment is created and closed, never rewritten.
  'clinicianAssignment.create',
  'clinicianAssignment.read',
  'clinicianAssignment.close',
  // A4.3 — insurance membership registration only. There is deliberately no delete, eligibility,
  // verify, primary/rank, authorization or claim permission.
  'insuranceMembership.create',
  'insuranceMembership.read',
  'insuranceMembership.update',
  // A4.4 — encounter registration and correction only. There is deliberately no delete,
  // eligibility, authorization, diagnosis, claim or submit permission.
  'encounter.create',
  'encounter.read',
  'encounter.update',
  // A4.5 — encounter diagnosis linkage: add, list, reorder and remove. There is deliberately no
  // delete, restore, primary/role, claim or coding-rule permission.
  'encounterDiagnosis.create',
  'encounterDiagnosis.read',
  'encounterDiagnosis.update',
  // A4.6 — encounter activity capture: add, list/get and remove. There is deliberately no delete,
  // restore, patch, pricing or claim permission.
  'encounterActivity.create',
  'encounterActivity.read',
  'encounterActivity.update',
] as const

export type PermissionCode = (typeof permissionCodes)[number]

export type AccessDecision =
  | { allowed: true; permissions: PermissionCode[] }
  | { allowed: false; reason: 'UNAUTHENTICATED' | 'NOT_MEMBER' | 'FORBIDDEN' }
